### ISSUE TITLE
mismatched types

### ISSUE THREAD

**Issue by michaelfaster** [imxood/test-egui#1]
Trying cargo run the test-egui, got the following issue. Can you give a help?
error[E0308]: mismatched types
   --> src/frame_history.rs:101:17
    |
101 |                 TextStyle::Monospace,
    |                 ^^^^^^^^^^^^^^^^^^^^ expected struct `eframe::egui::FontId`, found enum `eframe::egui::TextStyle`

**Comment by imxood** [comment]
@michaelfaster hi, thank you for using the code

I updated the code, and you need get the lastest code:
```sh
git pull
```
not necessary, update dependent libraries:
```sh
cargo update
```
 you can run the example:
```
cargo run --example test_shape1
cargo run --example test_shape
cargo run --example test_font
```

**Comment by michaelfaster** [comment]
@imxood thanks for the quick fixing and turning-around. The change works well.
